/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DS76
 */
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
public class StuRecord extends javax.swing.JFrame {
    String gender;
    String filename=null;
    byte [] person_image=null;
    

    /**
     * Creates new form StuRecord
     */
    public StuRecord() {
        initComponents();
        show_rec();
    }
    //for table
    public ArrayList<User> userList()
    {
        ArrayList userList=new ArrayList<>();
        try{
        Class.forName("com.mysql.jdbc.Driver");
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/avidb","root","india123");
       String query1="select * from sturec";
       Statement stmt=con.createStatement();
       ResultSet rs=stmt.executeQuery(query1);
       User user;
       while(rs.next())
       {
           user=new User(rs.getString("name"),rs.getString("college"),rs.getString("gender"),rs.getString("language"),rs.getString("stream"),rs.getBytes("images"));
       userList.add(user);
       }
        }
        
          catch(Exception e)
       {
           JOptionPane.showMessageDialog(null,e);
       }
        return userList;
    }
    public void show_rec()
    {
        ArrayList<User> list= userList();
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        Object[]row=new Object[5];
        for(int i=0;i<list.size();i++)
        {
         row[0]=list.get(i).getname();
         row[1]=list.get(i).getcollege();
         row[2]=list.get(i).getgender();
         row[3]=list.get(i).getlanguage();
         row[4]=list.get(i).getstream();
         model.addRow(row);
         
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        malebtn = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        collegetxt = new javax.swing.JTextField();
        femalebtn = new javax.swing.JRadioButton();
        streambtn = new javax.swing.JComboBox<>();
        javabtn = new javax.swing.JCheckBox();
        pythonbtn = new javax.swing.JCheckBox();
        addrec = new javax.swing.JButton();
        resetrec = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        photo = new javax.swing.JLabel();
        photobtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name");

        jLabel2.setText("College");

        buttonGroup1.add(malebtn);
        malebtn.setText("Male");

        jLabel3.setText("Gender");

        jLabel4.setText("Language");

        jLabel5.setText("Stream");

        nametxt.setText(" ");

        collegetxt.setText(" ");

        buttonGroup1.add(femalebtn);
        femalebtn.setText("Female");

        streambtn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Science", "Management", "BioTechnology", "Medical Science" }));

        javabtn.setText("Java");

        pythonbtn.setText("Python");

        addrec.setText("Add Record");
        addrec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrecActionPerformed(evt);
            }
        });

        resetrec.setText("Reset");
        resetrec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetrecActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "College", "Gender", "Language", "Stream"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        photo.setText(" ");
        photo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        photobtn.setText("Choose");
        photobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photobtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(119, 119, 119)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(streambtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(malebtn)
                                            .addComponent(javabtn))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                        .addComponent(pythonbtn))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(femalebtn)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                    .addGap(128, 128, 128)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nametxt, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                        .addComponent(collegetxt))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(addrec)
                        .addGap(72, 72, 72)
                        .addComponent(resetrec)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(photobtn)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(collegetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(malebtn)
                                .addComponent(femalebtn))
                            .addComponent(jLabel3))
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(javabtn)
                            .addComponent(pythonbtn))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(streambtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addrec)
                            .addComponent(resetrec))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(photobtn))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addrecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrecActionPerformed
        try{
        Class.forName("com.mysql.jdbc.Driver");
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/avidb","root","india123");
       String query="insert into sturec(name,college,gender,language,stream,images)values(?,?,?,?,?,?) ";
       PreparedStatement pst=con.prepareStatement(query);
       pst.setString(1,nametxt.getText());
        pst.setString(2,collegetxt.getText());
        if(malebtn.isSelected())
        {
            gender="Male";
        }
        if(femalebtn.isSelected())
        {
            gender="Female";
        }
        pst.setString(3,gender);
        
        String language="";
        if(javabtn.isSelected())
        {
            language=javabtn.getText()+" ";
        }
         if(pythonbtn.isSelected())
        {
            language=pythonbtn.getText()+" ";
        }
        pst.setString(4,language);
        String course;
        course=streambtn.getSelectedItem().toString();
        pst.setString(5,course);
        pst.setBytes(6,person_image);
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null,"Inserted successfully!!!");
        }
    
         catch(Exception e)
       {
           JOptionPane.showMessageDialog(null,e);
       }
    }//GEN-LAST:event_addrecActionPerformed

    private void resetrecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetrecActionPerformed
        nametxt.setText("");
        collegetxt.setText("");
        buttonGroup1.clearSelection();
        
    }//GEN-LAST:event_resetrecActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       int i=jTable1.getSelectedRow();
       TableModel model=jTable1.getModel();
       nametxt.setText(model.getValueAt(i,0).toString());
       collegetxt.setText(model.getValueAt(i,1).toString());
       String gender=model.getValueAt(i,2).toString();
         if(gender.equals("Male"))
         {
             malebtn.setSelected(true);
         }
         else
         {
             femalebtn.setSelected(true); 
         }
         
       String language=model.getValueAt(i,3).toString();
       switch(language)
       {
           case "Java ":
           javabtn.setSelected(true);
           pythonbtn.setSelected(false);
           break;
           case "Python ":
           pythonbtn.setSelected(true);
           javabtn.setSelected(false);
           break;
           default:
            javabtn.setSelected(true);   
            pythonbtn.setSelected(true);
           break;
       }
       String stream1=model.getValueAt(i,4).toString();
       switch(stream1)
       {
           case "Computer Science":
               streambtn.setSelectedIndex(0);
               break;
           case "Management":
               streambtn.setSelectedIndex(1);
               break;    
            case "Bio Technology":
               streambtn.setSelectedIndex(2);
               break;   
            case "Medical Science":
               streambtn.setSelectedIndex(3);
               break;  
               
       }
       byte[]img=(userList().get(i).getImage());
       ImageIcon imgicon=new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(photo.getWidth(),photo.getHeight(),Image.SCALE_SMOOTH));
      photo.setIcon(imgicon);
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void photobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photobtnActionPerformed
        // TODO add your handling code here:
      JFileChooser chooser=new JFileChooser();  
      chooser.showOpenDialog(null);
      File f=chooser.getSelectedFile();
      filename=f.getAbsolutePath();
      ImageIcon imgicon=new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(photo.getWidth(),photo.getHeight(),Image.SCALE_SMOOTH));
      photo.setIcon(imgicon);
      try
      {
       File image=new File(filename);
       FileInputStream fis=new FileInputStream(image);
       ByteArrayOutputStream bos=new ByteArrayOutputStream();
       byte[] buf=new byte[1024];
       for(int readNum;(readNum=fis.read(buf))!=-1;)
       {
           bos.write(buf,0,readNum);
       }
       person_image=bos.toByteArray();
      }
      catch(Exception e)
      {
          JOptionPane.showMessageDialog(null,e);
      }
      
      
    }//GEN-LAST:event_photobtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StuRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StuRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StuRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StuRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StuRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addrec;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField collegetxt;
    private javax.swing.JRadioButton femalebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JCheckBox javabtn;
    private javax.swing.JRadioButton malebtn;
    private javax.swing.JTextField nametxt;
    private javax.swing.JLabel photo;
    private javax.swing.JButton photobtn;
    private javax.swing.JCheckBox pythonbtn;
    private javax.swing.JButton resetrec;
    private javax.swing.JComboBox<String> streambtn;
    // End of variables declaration//GEN-END:variables
}
